### ISSUE TITLE
Number of pictures in a timeline page.

### ISSUE THREAD

**Issue by yo80106** [yujenyu/Group11_Project#13]
We have four pitures per timeline page. However, it will cause the last page leaving two empty spaces. Maybe it would be better to put five pictures in one page. What do you think?

**Comment by yujenyu** [comment]
In my opinion, I prefer five paintings in one page if its not hard to recompose.

**Comment by yo80106** [comment]
It is not hard to revise the setting. I will change the layout from four pictures to five. Cheers!

**Comment by yujenyu** [comment]
I've changed this page from 4 to 5 pics each.
