### ISSUE TITLE
Material for the Game: What's Wrong

### ISSUE THREAD

**Issue by ZevSong** [yujenyu/Group11_Project#14]
- [x] There are not enough pictures to make each period correspond to a painting
- [x] Each painting needs a short description
- [x] There should be a corresponding description for each different point

**Comment by yo80106** [comment]
Hi Song,
I agree with your first two points. However, I think we got the description for each difference, or I am misunderstanding your idea? Can you list the period that we have not covered so far? Thank you.

**Comment by ZevSong** [comment]
Hi Chen,
My bad. Regarding the last point, Renaissance's The School of Athens's description of the two statues is written together, just separate.
So we only need to do the first two.

**Comment by yujenyu** [comment]
Hi Song, could you just list the missing part and ill implement it asap.
