### ISSUE TITLE
Ask your opinion about the way to connect the backend and the frontend  

### ISSUE THREAD

**Issue by MasashiA** [yujenyu/Group11_Project#15]
Now I'm making a background system and its API and considering a way of data transmission system from backend server to frontend. To do this, I would like to confirm you some points below.

-  I think you have been implementing several (potential) pages for each game sections (i.e. Quiz and Detective). Then, can I assume each of those pages will separately have each endpoint (e.g. '/api/quiz1' or something) rather than a single endpoint with complex css? If so, I will implement methods in server.js (and api.js) file which is corresponding to each of those pages (i.e. I will implement a method like app.get("/api/quiz1", ...)).

- As for the data transmission, I'm thinking that I will make the API to respond a suitable data set in response to a url (endpoint) it receives. For example, if user (frontend side) calls "/api/quiz1" page, then backend-server returns a structure of data which has all related data for quiz1 (such as a path to the picture, a name of the picture, question sentences, etc). After that, frontend side will decode the data to get each element of the data structure (e.g. name of picture). Is it reasonable for you?

Probably my English is not clear, so if you have any question for clarification I'm happy to explain further. So, feel free to let me know your thinking!

**Comment by yo80106** [comment]
Hi Masa,
For my understanding so far, I think those two games will be like a page with buttons that user can click and trigger a pop-up window. The game content (quizz , picture, description, etc.) will be presented in that pop-up window. That is, all the data will be put in the single html file. However, if you think it is easier to implement the backend side by separating the content, I think we still can do that.

**Comment by MasashiA** [comment]
Thank you for the response! 
I think my understanding about the structure of  a single quiz (i.e. being put in a single html file) is consistent to your understanding. On the other hand, what I wanted to ask you is about a relationship among several quizzes. That is, I think there are several quizzes such as a quiz of an art work in Renaissance, Baroque, Impressionism, etc. In this case, do you plan to create these pages separately (i.e. different html file)?

**Comment by ZevSong** [comment]
Hi Masa,
For the function of the art detective, when the user clicks the button, we can get a number about the oil painting ID.
Now I am using this id to render different game pop-up interfaces, but this uses a long loop code to return data. It would be great if such a background system can be used to provide data.
I made a rough ER diagram of the data to be used([here](https://github.com/yujenyu/Group11_Project/raw/feature-artdetective/game_material/ER_for_ArtDetective.png)), hope it will be useful.

**Comment by MasashiA** [comment]
I will look at your code (in your branch)! Thanks!
