### ISSUE TITLE
Timeline page leave pop up window

### ISSUE THREAD

**Issue by yujenyu** [yujenyu/Group11_Project#17]
Hi guys, our pop up window in timeline page can only click the bottom side to leave. Could this bug be fixed as the last page? Thanks!

**Comment by ZevSong** [comment]
Change the width in the css file to a fixed value, but this will change the position of the pop-up box.

**Comment by ZevSong** [comment]
> Change the width in the css file to a fixed value, but this will change the position of the pop-up box.

To centre the pop-up box, add the code inside the css file：
```
position: fixed;
left:50%;
top:50%;
transform: translate(-50%,-50%);
```

**Comment by yujenyu** [comment]
Thank you so much!

**Comment by yo80106** [comment]
I will change the setting. Thank you for sharing @ZevSong.

**Comment by yujenyu** [comment]
Thank you guys, ive fixed this bug.
