### ISSUE TITLE
Naming our web

### ISSUE THREAD

**Issue by yujenyu** [yujenyu/Group11_Project#18]
Hi guys, before next meeting, could you guys think about 1 to 2 name of our web, eg. Art history 101, History on canvas, etc...... many thanks!

**Comment by MasashiA** [comment]
I'll bring some ideas then!  "History on canvas" is cool anyway =)

**Comment by MasashiA** [comment]
- Your Art Curator
- Dive into the Masterpiece
- Dive into the Art History
- Pocket Art Museum
- Portable Art Museum
- How old is your aesthetic sense?
- Which is your Favorite Art Movement?
- Thus Spake the Masterpiece
- Thus Spake the Art History
- Innovators in Art History
- Art History 101: lessons of art-thinking
- Art History 101: continuous revolution of beauty

**Comment by MasashiA** [comment]
- Your Art Curator
- Dive into the Masterpiece
- Dive into the Art History
- Pocket Art Museum
- Portable Art Museum
- How old is your aesthetic sense?
- Which is your Favorite Art Movement?
- Thus Spake the Masterpiece
- Thus Spake the Art History
- Innovators in Art History
- Art History 101: lessons of art-thinking
- Art History 101: continuous revolution of beauty

**Comment by yo80106** [comment]
Maybe we can create a poll for the naming.

**Comment by MasashiA** [comment]
How should we do this? do you want to use any good tools, or just commenting which you like on this discussion board?

**Comment by yujenyu** [comment]
/polls Option1 'Option 2' "Option 3"

# Automatically replace with the following markdown =>
[![](https://api.gh-polls.com/poll/01BY7ECS60GG8F9AR1VMR8745S/Option1)](https://api.gh-polls.com/poll/01BY7ECS60GG8F9AR1VMR8745S/Option1/vote)
[![](https://api.gh-polls.com/poll/01BY7ECS60GG8F9AR1VMR8745S/Option%202)](https://api.gh-polls.com/poll/01BY7ECS60GG8F9AR1VMR8745S/Option%202/vote)
[![](https://api.gh-polls.com/poll/01BY7ECS60GG8F9AR1VMR8745S/Option%203)](https://api.gh-polls.com/poll/01BY7ECS60GG8F9AR1VMR8745S/Option%203/vote)

**Comment by yo80106** [comment]
@yujenyu @MasashiA @ZevSong @LaurenCX make your preference for the name of our application. 
Every one shall vote for two titles.

[![](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/History%20on%20Canvas)](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/History%20on%20Canvas/vote)
[![](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Story%20on%20Canvas)](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Story%20on%20Canvas/vote)
[![](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Your%20Art%20Curator)](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Your%20Art%20Curator/vote)
[![](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Dive%20into%20the%20Masterpiece)](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Dive%20into%20the%20Masterpiece/vote)
[![](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Dive%20into%20the%20Art%20History)](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Dive%20into%20the%20Art%20History/vote)
[![](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Pocket%20Art%20Museum)](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Pocket%20Art%20Museum/vote)
[![](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Portable%20Art%20Museum)](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Portable%20Art%20Museum/vote)
[![](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Thus%20Spake%20the%20Masterpiece)](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Thus%20Spake%20the%20Masterpiece/vote)
[![](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Thus%20Spake%20the%20Art%20History)](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Thus%20Spake%20the%20Art%20History/vote)
[![](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Art%20History%20101)](https://api.gh-polls.com/poll/01F4HCGRVQC79C9EG1HKH8CEFR/Art%20History%20101/vote)

**Comment by MasashiA** [comment]
Good tool! How many votes does each person have?

**Comment by yo80106** [comment]
> * Your Art Curator
> * Dive into the Masterpiece
> * Dive into the Art History
> * Pocket Art Museum
> * Portable Art Museum
> * How old is your aesthetic sense?
> * Which is your Favorite Art Movement?
> * Thus Spake the Masterpiece
> * Thus Spake the Art History
> * Innovators in Art History
> * Art History 101: lessons of art-thinking
> * Art History 101: continuous revolution of beauty

Sorry, Masa, some of your suggestions, I think, are too long for fitting in the layout, so I modified them a little bit.

**Comment by MasashiA** [comment]
it's no problem cuz they were just brainstorming. Thank you for your coordination!
(sorry I'm not familiar with using github...)

**Comment by LaurenCX** [comment]
After members voted, "History on Canvas" got the most votes.
