### ISSUE TITLE
Preferred data structure

### ISSUE THREAD

**Issue by MasashiA** [yujenyu/Group11_Project#20]
In backend prototype, there're model.js files which define data structure and data.js files which hold actual data. The contents of these file are still sample fake data except file timeline which I implemented by my guess by looking at CY's html file. Actually, frontend files have become more and more complexed so I cannot see what kind of data structure is suitable and what data should be stored in the db without asking to frontend developers. 
So, I want to ask your opinion or I want you to modify model.js files and data.js files.

**Comment by MasashiA** [comment]
@ZevSong 
Hi, I saw the content of play.component.ts in the art-detective branch and have some questions for you. 
q1: (I asked this question yesterday but just to confirm.) Is play.component.ts the only file that contains the actual data? If there are (will be) other files, please let me know.
q2: Has the data structure not changed from the ER diagram you told me above? 
q3: As for how the data will be passed from the backend side, I'm thinking that it's one possible way that the backend sends a whole set of data at once when a user scrolls to the 2nd page of the art-detective page (i.e. when HTTP request "http://localhost:4200/#artdetective/1" calls), then play.component.ts file will pick out each portion of data and assign them to the certain variables in the file. Does this way make sense to you? 

Anyway, if the answer for q2 is "yes", I will make a sample data model and ask you if it'll be ok. On the other hand, because MongoDB is not a relational database (i.e. NoSQL) so its structure will not be exactly the same as the ER diagram (but effectively the same).

**Comment by ZevSong** [comment]
Hi Masa,
a1: Yes.
a2: Basically like this.
a3: I think it’s better to be able to return a set of data when the user requests to play.

**Comment by MasashiA** [comment]
Thanks! I responded to your message on Teams.
