### ISSUE TITLE
Failure of package.json file ?

### ISSUE THREAD

**Issue by MasashiA** [yujenyu/Group11_Project#21]
As I mentioned in the previous issue about pushing backend files, "ng serve" and "ng build" commands don't work in my environment with files pulled from current master branch.

I guess this is because there are some packages which failed to be incorporated in package.json and package-lack.json file (so erroneous node_modules folder was created when "npm install" run).

Does anyone solve the problem so far?

**Comment by yo80106** [comment]
Hi Masa,
I will fix the problem ASAP. Thank you for your reminder.

**Comment by yo80106** [comment]
Hi Masa,
I have updated the new version of the packages.json file under the dev branch. You can try to use [this file](https://github.com/yujenyu/Group11_Project/blob/f7b0099fc95044ac6d5356223042a92bf1b2943c/site/package.json) to set up Docker environment.

**Comment by MasashiA** [comment]
successfully compiled the angular files and executed both the frontend and the backend on the docker environment. I'm impressed!
