### ISSUE TITLE
Implementation of Service

### ISSUE THREAD

**Issue by MasashiA** [yujenyu/Group11_Project#22]
Did you add Service in angular files?  (c.f. week 7 worksheet)

**Comment by MasashiA** [comment]
If you haven't done it so far, I will implement related systems because it has somewhat affinity to the backend development.
(pls send me a reaction or comment if you see and agree in order to avoid overlap work)

**Comment by MasashiA** [comment]
@

**Comment by yo80106** [comment]
Hi Masa,
I think I did not add service when I was developing the frontend side. You can implement the related systems.

**Comment by LaurenCX** [comment]
Hi Masashi,
For the Fun Fact part, there is no Service being added as well. Thank you!

> If you haven't done it so far, I will implement related systems because it has somewhat affinity to the backend development.
> (pls send me a reaction or comment if you see and agree in order to avoid overlap work)

**Comment by MasashiA** [comment]
Thank you, guys! I believe Service is a data transmission interface of the frontend so we need to implement just for the art-detective for the time being. So, don't worry about it!
