### ISSUE TITLE
Invalid file name for Window

### ISSUE THREAD

**Issue by yo80106** [yujenyu/Group11_Project#24]
Hi Song,
I think you have created a folder with the name - Image_<500KB, which is invalid for Window. When I tried to pull your updated version, git was complaining about it. Could you please change the folder name? Thank you.

**Comment by ZevSong** [comment]
Sorry, it works for Mac...I will change it.

**Comment by yo80106** [comment]
Sorry, I need to be more specific. I think the error was caused by the invalid character "<".

**Comment by ZevSong** [comment]
It's changed, does it work now?👀

**Comment by yo80106** [comment]
This filename is invalid as well "game_material/Image500KB/Where_Do_We_Come_From?_What_Are_We?_Where_Are_We_Going?.jpg". The question mark is an invalid character for filename in Window.

**Comment by ZevSong** [comment]
How about now?

**Comment by yo80106** [comment]
Thank you @ZevSong . It works.
