### ISSUE TITLE
Content of the page are not placed at centre

### ISSUE THREAD

**Issue by yo80106** [yujenyu/Group11_Project#28]
After I merged the front page branch with the dev, I found that all the content are not placed at the centre as before. I think it is because the setting in the app.component.scss has been modified. @ZevSong, can you help?

**Comment by ZevSong** [comment]
Hi Chen,
I also found this problem and I just fixed this bug in art detective part.

**Comment by yo80106** [comment]
I fixed the problem. I updated the new version of app.component.scss under the dev branch.
