### ISSUE TITLE
Back-up strategy of displaying images

### ISSUE THREAD

**Issue by MasashiA** [yujenyu/Group11_Project#32]
I noticed that the frontend displays pictures of artworks by using URL (not image files). So, it would be better to prepare for the case these URLs will be expired. I think that, In Software Tools class, we learned the way to handle these situations (adding a small code when URLs don't work). 
Of course, it depends on the affordability, but I think if we do this, we can write about it in the documentation.

what do you think?

**Comment by yo80106** [comment]
Hi Masa,
I think it is a good idea. I will try to implement the function.
