### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by yo80106** [yujenyu/Group11_Project#33]
We almost finished the development stage of our project. We shall start to write the documentation. I created a [HackMD page](https://hackmd.io/Ep6W3Qa7QICfD4kVDFmTSg?view#) that we can co-edit the file and review other's writing.  I think it is more convenient than pull and push by using git.

- [x] Background and Motivation
- [x] System Implementation
- [x] UX Design
- [x] Sprints & Project Management
- [x] Evaluation
- [x] Conclusion

**Comment by yujenyu** [comment]
@yo80106 thank you!

**Comment by LaurenCX** [comment]
@yo80106 Great idea! Does it seem that only the owner can edit the documentation?

**Comment by yo80106** [comment]
Sorry, I changed the permission. Can you try again?

**Comment by LaurenCX** [comment]
For sure! Thank you!

**Comment by yo80106** [comment]
Thank you guys. I think we have finished writing the report!
