### ISSUE TITLE
Change background image for the front page.

### ISSUE THREAD

**Issue by yo80106** [yujenyu/Group11_Project#8]
Background image of the front page is using template image right now. We need to make a beautiful background image for our front page. @yujenyu can you help? 

The template image looks like:

![image](https://user-images.githubusercontent.com/8870177/115961155-15924f00-a50d-11eb-84e1-309fcebe47fd.png)

The front page looks like:

![image](https://user-images.githubusercontent.com/8870177/115960999-5e95d380-a50c-11eb-8828-3b5b72c9c0d9.png)

**Comment by yujenyu** [comment]
Sure, im trying to change the photo of front page. 

I got two ideas, one is just replace with a painting on front page, the other is combine the timeline paintings in a photo.

**Comment by yo80106** [comment]
The background image for the front page has decided to use a single picture.
